### PR TITLE
A simple check to kill the "`" check endless loop

### PR DESCRIPTION
**Pull request by iphands**
This patch simply checks for remaining "`" char in the "text" variable. If there are none, then the inner conditional that looks for a match is skipped. This prevents the conditional from being entered in cases where an endless loop could occur.

It makes the code below succeed where it would otherwise fail.

``` javascript
Markdown("##Usage\n###Simple, `standard, awesome\n~~~\njQuery('some_selector').meltdown();\n~~~\n");
```

### CODE REVIEW

**Comment by tanakahisateru** [comment]
I will check your contribution after finishing #27 .
Thanks,

**Comment by tanakahisateru** [comment]
Thanks for your greatest help,

But I'm thinking about to have a bit different solution. This bug is from only single line which cannot reproduce PHP version.

https://github.com/michelf/php-markdown/blob/x1.2.5/markdown.php#L1937

``` php
if (preg_match('{^(?>.+?|\n(?!\n))*?(?<!`)'.$tag_re.'(?!`)}', $text, $matches)) {
```

https://github.com/iphands/js-markdown-extra/blob/1.2.3/js-markdown-extra.js#L1953

``` javascript
if(matches = text.match(new RegExp('^(.+?|\\n[^\\n])*?[^`]' + tag_re + '[^`]'))) {
```

For more compatibility with PHP version, I want to confine the problem in their own line.

``` diff
         if (tag.charAt(0) == "`") {
             // Find corresponding end marker.
             tag_re = this._php_preg_quote(tag);
-            if(matches = text.match(new RegExp('^(.+?|\\n[^\\n])*?[^`]' + tag_re + '[^`]'))) {
+            if(
+                tag.substr(1).indexOf('`') != -1 && // [portiong note] To avoid JS's RegExp infinity loop.
+                (matches = text.match(new RegExp('^(.+?|\\n[^\\n])*?[^`]' + tag_re + '[^`]')))
+            ) {
                 // End marker found: pass text unchanged until marker.
                 parsed += tag + matches[0];
                 text = text.substr(matches[0].length);
```

@iphands, can you change your PR as above?

**Comment by iphands** [comment]
Works for me, thanks!

**Comment by tanakahisateru** [comment]
Thanks!

**Pull request merged**
